# Generated by Django 5.0.6 on 2026-05-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('principal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hod_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('hod_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='institutions.college')),
            ],
            options={
                'unique_together': {('college', 'name')},
            },
        ),
    ]
