# Generated by Django 5.0.6 on 2026-05-13 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('parent_topic', models.CharField(blank=True, max_length=200)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('is_weak', models.BooleanField(default=False)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject', 'topic'],
                'unique_together': {('user', 'subject', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='CognitiveEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('prerequisite', 'Prerequisite'), ('related', 'Related'), ('extension', 'Extension')], default='related', max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_edges', to=settings.AUTH_USER_MODEL)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='cognitive.cognitivenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='cognitive.cognitivenode')),
            ],
            options={
                'unique_together': {('user', 'source_node', 'target_node')},
            },
        ),
    ]
