# Generated by Django 5.0.6 on 2026-05-13 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('test_average', models.FloatField(default=0.0)),
                ('last_studied', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mastery_score'],
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
